/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  SeacowsComplement,
  SeacowsComplementInterface,
} from "../SeacowsComplement";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "COMPLEMENT_PRECISION",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenAmountOut",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_nftAmountOut",
        type: "uint256",
      },
    ],
    name: "getComplemenetedAssetsOut",
    outputs: [
      {
        internalType: "uint256",
        name: "tokenAmountOut",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "nftAmountOut",
        type: "uint256",
      },
      {
        internalType: "int256",
        name: "tokenComplementAdjusted",
        type: "int256",
      },
      {
        internalType: "uint256",
        name: "nftComplementAdjusted",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nftComplement",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "tokenComplement",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506102fd806100206000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c806369eedcde146100515780639a2fe1bd146100895780639e75baa71461009b578063a4ac5c1d146100aa575b600080fd5b61006461005f3660046101e1565b6100b2565b6040805194855260208501939093529183015260608201526080015b60405180910390f35b6001545b604051908152602001610080565b61008d670de0b6b3a764000081565b60005461008d565b6000808080806100c287876101c0565b90506000866001546100d49190610219565b9050670de0b6b3a7640000811061017657610101670de0b6b3a76400006100fb83826101c0565b906101d5565b945061010d858261022c565b925086851061014a576000610126836100fb8a8961022c565b9050610132818a61022c565b965080600054610142919061023f565b9450506101b5565b600061015a836100fb888b61022c565b9050610166818a610219565b9650806000546101429190610267565b866001546101849190610219565b6000955092508461019588846101d5565b90506101a1818a610219565b9650806000546101b19190610267565b9450505b505092959194509250565b60006101cc828461028e565b90505b92915050565b60006101cc82846102b0565b600080604083850312156101f457600080fd5b50508035926020909101359150565b634e487b7160e01b600052601160045260246000fd5b808201808211156101cf576101cf610203565b818103818111156101cf576101cf610203565b808201828112600083128015821682158216171561025f5761025f610203565b505092915050565b818103600083128015838313168383128216171561028757610287610203565b5092915050565b6000826102ab57634e487b7160e01b600052601260045260246000fd5b500490565b80820281158282048414176101cf576101cf61020356fea26469706673582212201281d419d400dbada852940561e989d43a33fb3816540a1bf851515fde4dac5e64736f6c63430008120033";

export class SeacowsComplement__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<SeacowsComplement> {
    return super.deploy(overrides || {}) as Promise<SeacowsComplement>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): SeacowsComplement {
    return super.attach(address) as SeacowsComplement;
  }
  connect(signer: Signer): SeacowsComplement__factory {
    return super.connect(signer) as SeacowsComplement__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SeacowsComplementInterface {
    return new utils.Interface(_abi) as SeacowsComplementInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SeacowsComplement {
    return new Contract(address, _abi, signerOrProvider) as SeacowsComplement;
  }
}
